<?
$MESS['SMARTSEO_PAGE_TITLE'] = 'Sitemap';
$MESS['SMARTSEO_ACTION_TYPE_EDIT'] = 'Editing';
$MESS['SMARTSEO_ACTION_TYPE_ADD'] = 'Add';
$MESS['SMARTSEO_ACTION_BACK_LIST'] = 'Back to List';
$MESS['SMARTSEO_ELEMENT_DEFAULT_NAME'] = '[#ID#] sitemap';

$MESS['SMARTSEO_MENU_ACTIONS'] = 'Actions';
$MESS['SMARTSEO_MENU_ADD'] = 'Add Sitemap';
$MESS['SMARTSEO_MENU_DELETE'] = 'Delete Sitemap';
$MESS['SMARTSEO_MENU_COPY'] = 'Copy Sitemap';

$MESS['SMARTSEO_FORM_ENTITY_ID'] = 'ID';
$MESS['SMARTSEO_FORM_ENTITY_ACTIVE'] = 'Activity';
$MESS['SMARTSEO_FORM_ENTITY_SITE_ID'] = 'Site';
$MESS['SMARTSEO_FORM_ENTITY_NAME'] = 'Name';
$MESS['SMARTSEO_FORM_ENTITY_DATE_CREATE'] = 'Created Date';
$MESS['SMARTSEO_FORM_ENTITY_DATE_CHANGE'] = 'Date modified';
$MESS['SMARTSEO_FORM_ENTITY_DATE_LAST_LAUNCH'] = 'Last Launched Date';
$MESS['SMARTSEO_FORM_ENTITY_PROTOCOL'] = 'Protocol';
$MESS['SMARTSEO_FORM_ENTITY_DOMAIN'] = 'Site Domain';
$MESS['SMARTSEO_FORM_ENTITY_SITE_ADDRESS'] = 'Site URL';
$MESS['SMARTSEO_FORM_ENTITY_SITEMAP_FILE'] = 'Path to sitemap file';
$MESS['SMARTSEO_FORM_ENTITY_IN_ROBOTS'] = 'Add map to robots.txt';
$MESS['SMARTSEO_FORM_ENTITY_IN_INDEX_SITEMAP'] = 'Include Map in Index File';
$MESS['SMARTSEO_FORM_ENTITY_INDEX_SITEMAP_FILE'] = 'Path to sitemap index file';
$MESS['SMARTSEO_FORM_ENTITY_MAIN_SITEMAP_ADDRESS'] = 'Main sitemap URL';
$MESS['SMARTSEO_FORM_ENTITY_UPDATE_SITEMAP_INDEX_FIELD'] = 'Update the index file after the map is generated by the SEO module [seo]';
$MESS['SMARTSEO_FORM_ENTITY_UPDATE_SITEMAP_FILE_FIELD'] = 'Update map file after generating landing pages';

$MESS['SMARTSEO_FORM_VALUE_DATE_LAST_LAUNCH_NEVER'] = 'Never';

$MESS['SMARTSEO_FORM_GROUP_SETTINGS'] = 'Event Handling';

$MESS['SMARTSEO_FORM_BTN_SAVE'] = 'Save';
$MESS['SMARTSEO_FORM_BTN_APPLY'] = 'Apply';
$MESS['SMARTSEO_FORM_BTN_CANCEL'] = 'Cancel';
$MESS['SMARTSEO_FORM_CHECKBOX_GENERATE_ADD_SITEMAP'] = 'Create Sitemap File';
$MESS['SMARTSEO_FORM_CHECKBOX_GENERATE_UPDATE_SITEMAP'] = 'Update sitemap file';

$MESS['SMARTSEO_FORM_HINT_SAVE'] = 'Save and Return';
$MESS['SMARTSEO_FORM_HINT_APPLY'] = 'Save and Stay Fit';
$MESS['SMARTSEO_FORM_HINT_CANCEL'] = 'Do not save and return';
$MESS['SMARTSEO_FORM_HINT_SITEMAP'] = 'Save and Recreate Sitemap File';

$MESS['SMARTSEO_TAB_GENERAL_NAME'] = 'Sitemap';
$MESS['SMARTSEO_TAB_GENERAL_TITLE'] = 'General Settings';
$MESS['SMARTSEO_TAB_CONDITION_NAME'] = 'Map Conditions';
$MESS['SMARTSEO_TAB_CONDITION_TITLE'] = 'List of conditional links';

$MESS['SMARTSEO_POPUP_BTN_DELETE'] = 'Delete';
$MESS['SMARTSEO_POPUP_BTN_CANCEL'] = 'Cancel';
$MESS['SMARTSEO_POPUPMESSGE_DELETE'] = 'All information associated with this sitemap will be deleted! <br> Continue? ';

$MESS['SMARTSEO_HINT_IN_INDEX_SITEMAP'] = 'This is an XML file that is structured almost exactly like a regular Sitemap file. The following XML tags are used in the index files - sitemapindex, sitemap, loc ';
$MESS['SMARTSEO_HINT_IN_ROBOTS'] = 'If <b> <Include map in index file> </b> is selected then the Sitemap of the sitemap index file will be added to robots.txt';
