<?php

require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");

$APPLICATION->SetPageProperty("BLOG_PAGE", "Y");

$APPLICATION->SetPageProperty(
    "title",
    "Полезные статьи об электромотоциклах - официальный представитель Super Soco в РФ +7 499 704-42-08"
);

$APPLICATION->SetPageProperty(
    "description",
    "Статьи об электромотоциклах Super Soco. Электромотоциклы – это самый современный вид двухколесного транспорта, который работает исключительно на электричестве."
);

?><? $APPLICATION->IncludeComponent(
	"bitrix:news", 
	"blog", 
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BIG_GALLERY_PROP_CODE" => "PHOTOS",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y",
		"DETAIL_BLOCKS_ALL_ORDER" => "order_form,desc,goods,tizers,faq,char,sale,reviews,big_gallery,video,services,articles,docs,dops,comments",
		"DETAIL_BLOCKS_ORDER" => "tizers,tabs,big_gallery,services,articles,partners,vacancy,goods,comments",
		"DETAIL_BLOCKS_TAB_ORDER" => "desc,char,video,docs,reviews,dops",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "ID",
			1 => "TAGS",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_PICTURE",
			5 => "DATE_ACTIVE_FROM",
			6 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "PHOTOPOS",
			1 => "VIDEO_IFRAME",
			2 => "VIDEO",
			3 => "LINK_GOODS_FILTER",
			4 => "LINK_ARTICLES",
			5 => "LINK_TIZERS",
			6 => "LINK_GOODS",
			7 => "LINK_SERVICES",
			8 => "LINK_FAQ",
			9 => "LINK_VACANCY",
			10 => "LINK_PARTNERS",
			11 => "LINK_REVIEWS",
			12 => "AUTHOR",
			13 => "DATA",
			14 => "SITE",
			15 => "ORDERER",
			16 => "FORM_QUESTION",
			17 => "FORM_ORDER",
			18 => "PRICE",
			19 => "PRICEOLD",
			20 => "ECONOMY",
			21 => "LINK_STUDY",
			22 => "FOR_SHOW_1",
			23 => "FOR_SHOW_5",
			24 => "FOR_SHOW_2",
			25 => "FOR_SHOW_3",
			26 => "FOR_SHOW_4",
			27 => "FOR_SHOW_6",
			28 => "FOR_SHOW_7",
			29 => "FOR_SHOW_8",
			30 => "DOCUMENTS",
			31 => "PHOTOS",
			32 => "STATUS",
			33 => "ARTICLE",
			34 => "DATE_COUNTER",
			35 => "LINK_SKU",
			36 => "PRICE_CURRENCY",
			37 => "DEPTH",
			38 => "GRUZ_STRELI",
			39 => "GRUZ",
			40 => "DLINA_STRELI",
			41 => "VOLUME",
			42 => "RECOMMEND",
			43 => "SPEED",
			44 => "WIDTH_PROHOD",
			45 => "WIDTH_PROEZD",
			46 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"DETAIL_USE_COMMENTS" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"DOCS_PROP_CODE" => "DOCUMENTS",
		"ELEMENT_TYPE_VIEW" => "FROM_MODULE",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "15",
		"IBLOCK_TYPE" => "aspro_lite_content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DATE_ACTIVE_FROM",
			5 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "POSITION_BLOCK",
			2 => "PERIOD",
			3 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"NUM_DAYS" => "30",
		"NUM_NEWS" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "main",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTIES_DISPLAY_TYPE" => "TABLE",
		"SECTION_ELEMENTS_TYPE_VIEW" => "FROM_MODULE",
		"SEF_FOLDER" => "/blog/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_BIG_GALLERY" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"SHOW_DOPS" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"TOP_GALLERY_PROP_CODE" => "-",
		"TYPE_BIG_GALLERY" => "BIG",
		"T_ARTICLES" => "",
		"T_BIG_GALLERY" => "Фотогалерея",
		"T_CHAR" => "",
		"T_DESC" => "",
		"T_DOCS" => "",
		"T_GOODS" => "Электромотоциклы Super Soco",
		"T_PARTNERS" => "",
		"T_REVIEWS" => "",
		"T_SALE" => "",
		"T_SERVICES" => "",
		"T_VACANCY" => "",
		"T_VIDEO" => "",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "Y",
		"YANDEX" => "N",
		"COMPONENT_TEMPLATE" => "blog",
		"T_DOPS" => "",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"COMMENTS_COUNT" => "5",
		"DETAIL_BLOG_TITLE" => "Комментарии",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_FB_USE" => "N",
		"SHOW_CATEGORY" => "Y",
		"DETAIL_USE_TAGS" => "Y",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SKU_IBLOCK_ID" => "14",
		"SKU_PROPERTY_CODE" => array(
			0 => "FORM_ORDER",
			1 => "STATUS",
			2 => "PRICE_CURRENCY",
			3 => "PRICE",
			4 => "PRICEOLD",
			5 => "ECONOMY",
			6 => "COLOR",
			7 => "GOST",
			8 => "DLINA",
			9 => "VYLET_STRELY",
			10 => "MARK_STEEL",
			11 => "WIDTH",
		),
		"SKU_TREE_PROPS" => array(
			0 => "COLOR",
			1 => "DIAMETER",
			2 => "DLINA",
			3 => "VYLET_STRELY",
			4 => "THICKNESS_STEEL",
			5 => "WIDTH",
		),
		"SKU_SORT_FIELD" => "sort",
		"SKU_SORT_ORDER" => "asc",
		"SKU_SORT_FIELD2" => "name",
		"SKU_SORT_ORDER2" => "asc",
		"USE_REVIEW" => "N",
		"T_FAQ" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"detail" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		)
	),
	false
); ?><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>