<?php
define('SMARTSEO_MORPHOLOGY_MASCULINUM', 'МР');
define('SMARTSEO_MORPHOLOGY_FEMINUM', 'ЖР');
define('SMARTSEO_MORPHOLOGY_NEUTRUM', 'СР');
define('SMARTSEO_MORPHOLOGY_NOUN', 'С');
define('SMARTSEO_MORPHOLOGY_ADJ_FULL', 'П');
define('SMARTSEO_MORPHOLOGY_ADJ_SHORT', 'КР_ПРИЛ');
define('SMARTSEO_MORPHOLOGY_VERB', 'Г');
define('SMARTSEO_MORPHOLOGY_SINGULAR', 'ЕД');
define('SMARTSEO_MORPHOLOGY_PLURAL', 'МН');
