<?EventMessageThemeCompiler::includeComponent(
    "bitrix:sale.basket.basket.small.mail",
    "aspro_lite_cart",
    Array(
        "COLUMNS_LIST" => array(
            "NAME",
            "DISCOUNT_FORMATED",
            "TYPE",
            "PRICE_FORMATED",
            "QUANTITY_FORMATED",
            "SUM",
            "DETAIL_PICTURE",
            "PREVIEW_PICTURE",
            "PROPERTY_COLOR_REF",
            "PROPERTY_SIZES",
            "PROPERTY_VOLUME",
            "PROPERTY_SIZES5",
            "PROPERTY_SIZES3",
            "PROPERTY_SIZES4",
        ),
        "COMPONENT_TEMPLATE" => "aspro_lite_cart",
        "COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
        "PATH_TO_BASKET" => "%BASKET_PAGE_URL%",
        "PATH_TO_ORDER" => "%ORDER_PAGE_URL%",
        "SHOW_DELAY" => "N",
        "SHOW_NOTAVAIL" => "Y",
        "SHOW_SUBSCRIBE" => "N",
        "USER_ID" => "{#USER_ID#}",
        "TITLE" => "%BASKET_TITLE%",
        "NOTE" => "%BASKET_NOTE%",
        "SHOW_BUTTON" => "%SHOW_BUTTON%",
        "BUTTON_TITLE" => "%BUTTON_TITLE%",
        "BUTTON_LINK" => "%BASKET_PAGE_URL%",
        "SITE_ID" => "%SITE_ID%",
        "SITE_ADDRESS" => "%SITE_ADDRESS%",
        "BASE_COLOR" => "%BASE_COLOR%",
    )
);?>