<?EventMessageThemeCompiler::includeComponent(
	"bitrix:sale.personal.order.detail.mail",
	"aspro_lite_order",
	Array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
        "COMPONENT_TEMPLATE" => "aspro_lite_order",
		"CUSTOM_SELECT_PROPS" => array(
            "NAME",
            "DISCOUNT_PRICE_PERCENT_FORMATED",
            "TYPE",
            "PRICE_FORMATED",
            "QUANTITY",
            "PICTURE",
            "PROPERTY_COLOR_REF",
            "PROPERTY_SIZES",
            "PROPERTY_VOLUME",
            "PROPERTY_SIZES5",
            "PROPERTY_SIZES3",
            "PROPERTY_SIZES4",
        ),
		"ID" => "{#ORDER_ID#}",
		"PATH_TO_CANCEL" => "%PERSONAL_PAGE_URL%cancel/ORDER_ID",
		"PATH_TO_LIST" => "%PERSONAL_PAGE_URL%orders/",
		"PATH_TO_PAYMENT" => "%PERSONAL_PAGE_URL%payment/index.php",
		"PICTURE_HEIGHT" => "150",
		"PICTURE_RESAMPLE_TYPE" => "1",
		"PICTURE_WIDTH" => "150",
		"PROP_1" => array(),
		"PROP_2" => array(),
		"SHOW_ORDER_BASE" => "N",
		"SHOW_ORDER_BASKET" => "Y",
		"SHOW_ORDER_BUYER" => "N",
		"SHOW_ORDER_DELIVERY" => "N",
		"SHOW_ORDER_PARAMS" => "N",
		"SHOW_ORDER_PAYMENT" => "N",
		"SHOW_ORDER_USER" => "N",
		"SHOW_ORDER_SUM" => "%SHOW_ORDER_SUM%",
        "TITLE" => "%ORDER_TITLE%",
		"NOTE" => "%ORDER_NOTE%",
        "SITE_ID" => "%SITE_ID%",
        "SITE_ADDRESS" => "%SITE_ADDRESS%",
        "BASE_COLOR" => "%BASE_COLOR%",
        "SHOW_REVIEW_BUTTON" => "%SHOW_REVIEW_BUTTON%",
        "REVIEW_BUTTON_TITLE" => "%REVIEW_BUTTON_TITLE%",
	)
);?>