<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Производители");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"brands", 
	array(
		"IBLOCK_ID" => "8",
		"IBLOCK_TYPE" => "aspro_lite_content",
		"COMPONENT_TEMPLATE" => "brands",
		"NEWS_COUNT" => "20",
		"USE_SEARCH" => "N",
		"SECTION_ELEMENTS_TYPE_VIEW" => "FROM_MODULE",
		"ELEMENT_TYPE_VIEW" => "FROM_MODULE",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_TITLE" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"SHOW_DETAIL_LINK" => "Y",
		"USE_SHARE" => "Y",
		"DISPLAY_NAME" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_TEXT",
			3 => "DETAIL_PICTURE",
			4 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "SITE",
			1 => "EMAIL",
			2 => "PHONE",
			3 => "STATUS",
			4 => "ARTICLE",
			5 => "PRICE",
			6 => "PRICEOLD",
			7 => "FILTER_PRICE",
			8 => "ECONOMY",
			9 => "RECOMMEND",
			10 => "FORM_QUESTION",
			11 => "FORM_ORDER",
			12 => "BEST_ITEM",
			13 => "BRAND",
			14 => "PRICE_CURRENCY",
			15 => "DATE_COUNTER",
			16 => "HIT",
			17 => "DEPTH",
			18 => "GRUZ_STRELI",
			19 => "GRUZ",
			20 => "DLINA_STRELI",
			21 => "VOLUME",
			22 => "WIDTH_PROHOD",
			23 => "WIDTH_PROEZD",
			24 => "DLINA_STRELI",
			25 => "SPEED",
			26 => "DOCUMENTS",
			27 => "LINK_SKU",
			28 => "PRICE_CURRENCY",
			29 => "DEPTH",
			30 => "GRUZ_STRELI",
			31 => "GRUZ",
			32 => "DLINA_STRELI",
			33 => "VOLUME",
			34 => "RECOMMEND",
			35 => "SPEED",
			36 => "WIDTH_PROHOD",
			37 => "WIDTH_PROEZD",
			38 => "",
		),
		"T_DOCS" => "",
		"DOCS_PROP_CODE" => "DOCUMENTS",
		"SHOW_LINK_GOODS" => "Y",
		"T_LINK_GOODS" => "",
		"LINK_GOODS_IBLOCK_ID" => "13",
		"LINK_GOODS_PROP_CODE" => "BRAND",
		"T_COMMENTS" => "",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_BLOG_USE" => "Y",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"COMMENTS_COUNT" => "5",
		"DETAIL_BLOG_TITLE" => "Комментарии",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"DETAIL_VK_USE" => "Y",
		"DETAIL_VK_TITLE" => "Вконтакте",
		"DETAIL_VK_API_ID" => "API_ID",
		"DETAIL_FB_USE" => "Y",
		"DETAIL_FB_TITLE" => "Facebook",
		"DETAIL_FB_APP_ID" => "API_ID",
		"DETAIL_BLOCKS_ORDER" => "link_sections,link_goods,docs,comments",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => "main",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SET_STATUS_404" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SEF_FOLDER" => "/brands/",
		"T_LINK_SECTIONS" => "",
		"DEPTH_LEVEL_BRAND" => "2",
		"SKU_IBLOCK_ID" => "14",
		"SKU_PROPERTY_CODE" => array(
			0 => "MORE_PHOTO",
			1 => "COLOR_REF",
		),
		"SKU_TREE_PROPS" => array(
			0 => "COLOR_REF",
		),
		"SKU_SORT_FIELD" => "sort",
		"SKU_SORT_ORDER" => "asc",
		"SKU_SORT_FIELD2" => "name",
		"SKU_SORT_ORDER2" => "asc",
		"USE_REVIEW" => "N",
		"SORT_PROP" => array(
			0 => "SHOWS",
			1 => "NAME",
			2 => "PRICES",
			3 => "QUANTITY",
		),
		"SORT_PROP_DEFAULT" => "SHOWS",
		"SORT_DIRECTION" => "desc",
		"VIEW_TYPE" => "table",
		"SECTION_LIST_DISPLAY_TYPE" => "3",
		"PRICE_CODE" => array(
			0 => "BASE",
			1 => "OPT",
			2 => "MSC",
			3 => "EKB",
			4 => "MAGNITOGORSK",
			5 => "",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"SORT_PRICES" => "REGION_PRICE",
		"SORT_REGION_PRICE" => "BASE",
		"FILTER_NAME" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"NUM_NEWS" => "20",
		"NUM_DAYS" => "30",
		"YANDEX" => "N",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>